---
title: "`r params$year` NEFMC Weights"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
params: # NA because they will be replaced by the shiny app parameters
    year: NA
    weights: NA 
---
```{r setup, include=FALSE}
# set echo in all code chunks so they are not included in the output file
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE) 
# library(gt)
library(tidyverse)
# library(flextable)
library(kableExtra)
```

```{r weights}
levels <- c("biomass", "recruitment", "climate", "commercial", "recreational")

averages <- params$weights |>
    summarise(weight = mean(weight), .by = c(report_year, factor)) |> 
    mutate(factor = str_c(factor, "avg", sep = "_"))

wts_w_avg <- params$weights |> 
    bind_rows(averages)

wts_w_avg <- wts_w_avg[c(1:21,106, 22:42, 107, 43:63, 108, 64:84, 109, 85:105, 110),]

wts_w_avg |> 
    mutate(report_year = case_when(
        factor %in% c("biomass_avg", "climate_avg", "recruitment_avg", "commercial_avg", "recreational_avg") ~ "Average", 
        TRUE ~ report_year), 
        weight = round(weight,2)) |> 
    select(!factor) |> 
    rename("Action Year" = report_year) |> 
    rename("Weight" = weight) |>
    knitr::kable(booktabs = T) |> 
        kable_styling(latex_options = c("hold_position", "scale_down", "repeat_header"), position = "center", fixed_thead = T, font_size = 12) |> 
        pack_rows("Biomass", 1,21, background = "#DDDDDD") |> 
        row_spec(21, hline_after = TRUE) |>
        row_spec(22, italic = TRUE, align = "r") |>
        pack_rows("Recruitment", 23,43, background = "#DDDDDD") |> 
        row_spec(43, hline_after = TRUE) |>
        row_spec(44, italic = TRUE, align = "r") |>
        pack_rows("Climate", 45,66, background = "#DDDDDD") |>
        row_spec(65, hline_after = TRUE) |>
        row_spec(66, italic = TRUE, align = "r") |>
        pack_rows("Commercial", 67,88, background = "#DDDDDD") |> 
        row_spec(87, hline_after = TRUE) |>
        row_spec(88, italic = TRUE, align = "r") |>
        pack_rows("Recreational", 89,110, background = "#DDDDDD") |> 
        row_spec(109, hline_after = TRUE) |>
        row_spec(110, italic = TRUE, align = "r") |> 
        column_spec(1, width = "5cm")


```

